version: "3.7"
services:
  app:
    container_name: app
    build:
      dockerfile: ./php/Dockerfile
    ports:
      - 9000:80
    volumes:
      - ./app:/var/www/
    depends_on:
      - database
      - redis
    links:
      - database
      - redis
    restart: unless-stopped
  web:
    container_name: web
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/
    depends_on:
      - app
      - database
      - redis
    links:
      - app
    restart: unless-stopped
  database:
    container_name: database
    build:
      dockerfile: ./database/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./database/mariadb:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345600
      MYSQL_DATABASE: staj_rapor_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345600
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 9500:80
    depends_on:
      - database
    links:
      - database
    restart: unless-stopped
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 12345600
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 100000000

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    depends_on:
      - database
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: 123456
      REDIS_PORT: 6379
