FROM mariadb:latest

ENV MYSQL_USER=root
ENV MYSQL_ROOT_PASSWORD=123456
ENV MYSQL_DATABASE=test_db

VOLUME [ "./mariadbdata/", "/var/lib/mysql" ]

EXPOSE 3306

# build command:
# docker build -t mariadb:latest -f .dockerfile .





